###
POST http://localhost:5000/api/register HTTP/1.1
Content-Type: application/json

 {
    "name":"pepito",
    "lastname":"pepe",
    "email":"admiiin@admin.com",
    "password":"admin123",
    "token":"asdasdasij123",
    "phone":"1234567",
    "confim":"true"
}

###
GET http://localhost:5000/api/getAllUsers HTTP/1.1

###
GET http://localhost:5000/api/getUser/627ac0989e9e2d5587a268b3 HTTP/1.1

###
POST http://localhost:5000/api/login HTTP/1.1
Content-Type: application/json

    {
    "email":"admiiin@admin.com",
    "password":"admin1234"
}
###
GET http://localhost:5000/ HTTP/1.1
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjI4MzI1NjFlOGI5MTVlNWYyMTFlOWEwIiwiZW1haWwiOiJhZG1paWluQGFkbWluLmNvbSIsImlhdCI6MTY1Mjc2MzkwNywiZXhwIjoxNjUyNzcxMTA3fQ.O-1L-6u8mwFmqG2A5X5iQV1U_iETWWgugs87SEbLtls
 
